[project]
name = "1104-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "joblib>=1.4.2",
    "jupyter>=1.1.1",
    "pytesseract>=0.3.13",
    "tqdm>=4.66.6",
]
